name = "gaming-pe-pal-website"
main = "worker/index.ts"
compatibility_date = "2026-07-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[observability]
enabled = true

[triggers]
crons = ["*/1 * * * *"]

[vars]
PALWORLD_RCON_HOST = "174.138.184.118"
PALWORLD_RCON_PORT = "27050"
PALWORLD_REST_URL = "http://174.138.184.118:27051/v1/api"
PALWORLD_MAX_PLAYERS = "24"

[[kv_namespaces]]
binding = "SERVER_STATUS"
id = "a1ba62edd24f45798ef1c0141490d440"

[[routes]]
pattern = "gaming-pe-pal.com"
custom_domain = true
